#ifndef TERRARIUM_NOVA_CONFIG_H
#define TERRARIUM_NOVA_CONFIG_H

#define NOVA_SERVICE_NAME "terrarium-nova"
#define NOVA_DEFAULT_WIDTH 1280
#define NOVA_DEFAULT_HEIGHT 720
#define NOVA_MAX_WORKSPACES 4
#define NOVA_LAUNCHER_WIDGET_ID 1u

#endif
