#ifndef TERRARIUM_SYSTEM_RUNTIME_SYSCALL_H
#define TERRARIUM_SYSTEM_RUNTIME_SYSCALL_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define TERRARIUM_SYSCALL_ABI_VERSION 1u

typedef enum terra_syscall_id {
    TERRA_SYSCALL_NOP = 0,
    TERRA_SYSCALL_ABI_INFO = 1,
    TERRA_SYSCALL_TIME_NS = 2,
    TERRA_SYSCALL_TIME_MS = 3,
    TERRA_SYSCALL_TIME_RESOLUTION = 4,

    TERRA_SYSCALL_FS_BASE = 100,
    TERRA_SYSCALL_FS_OPEN = 100,
    TERRA_SYSCALL_FS_CLOSE = 101,
    TERRA_SYSCALL_FS_READ = 102,
    TERRA_SYSCALL_FS_WRITE = 103,
    TERRA_SYSCALL_FS_SEEK = 104,
    TERRA_SYSCALL_FS_STAT = 105,

    TERRA_SYSCALL_PROC_BASE = 200,
    TERRA_SYSCALL_PROC_SPAWN = 200,
    TERRA_SYSCALL_PROC_WAIT = 201,
    TERRA_SYSCALL_PROC_KILL = 202,
    TERRA_SYSCALL_PROC_INFO = 203,

    TERRA_SYSCALL_MEM_BASE = 300,
    TERRA_SYSCALL_IPC_BASE = 400,
    TERRA_SYSCALL_NET_BASE = 500,
    TERRA_SYSCALL_NET_IF_LIST = 500,
    TERRA_SYSCALL_NET_ROUTE_LIST = 501,
    TERRA_SYSCALL_NET_ROUTE_ADD = 502,
    TERRA_SYSCALL_NET_DNS_GET = 503,
    TERRA_SYSCALL_NET_DNS_SET = 504,
    TERRA_SYSCALL_NET_FIREWALL_LIST = 505,
    TERRA_SYSCALL_NET_FIREWALL_ADD = 506,
    TERRA_SYSCALL_NET_SOCKET_LIST = 507,
    TERRA_SYSCALL_NET_PACKET_DIAG = 508,
    TERRA_SYSCALL_NET_PING = 509,
    TERRA_SYSCALL_SECURITY_BASE = 600,

    TERRA_SYSCALL_HARDWARE_BASE = 700,
    TERRA_SYSCALL_HWINFO = 700,

    TERRA_SYSCALL_SERVICE_BASE = 800,
    TERRA_SYSCALL_SERVICE_START = 800,
    TERRA_SYSCALL_SERVICE_STOP = 801,
    TERRA_SYSCALL_SERVICE_STATUS = 802,
    TERRA_SYSCALL_SERVICE_LIST = 803
} terra_syscall_id_t;

long terra_syscall(uint32_t number, uintptr_t a0, uintptr_t a1, uintptr_t a2,
                   uintptr_t a3, uintptr_t a4, uintptr_t a5);

#ifdef __cplusplus
}
#endif

#endif
