#ifndef TERRARIUM_EXCEPTIONS_H
#define TERRARIUM_EXCEPTIONS_H

#define TERRA_EXCEPTION_DIVIDE_ERROR 0
#define TERRA_EXCEPTION_DEBUG 1
#define TERRA_EXCEPTION_NMI 2
#define TERRA_EXCEPTION_BREAKPOINT 3
#define TERRA_EXCEPTION_OVERFLOW 4
#define TERRA_EXCEPTION_BOUND_RANGE 5
#define TERRA_EXCEPTION_INVALID_OPCODE 6
#define TERRA_EXCEPTION_DEVICE_NOT_AVAILABLE 7
#define TERRA_EXCEPTION_DOUBLE_FAULT 8
#define TERRA_EXCEPTION_INVALID_TSS 10
#define TERRA_EXCEPTION_SEGMENT_NOT_PRESENT 11
#define TERRA_EXCEPTION_STACK_SEGMENT_FAULT 12
#define TERRA_EXCEPTION_GENERAL_PROTECTION 13
#define TERRA_EXCEPTION_PAGE_FAULT 14
#define TERRA_EXCEPTION_X87_FLOATING_POINT 16
#define TERRA_EXCEPTION_ALIGNMENT_CHECK 17
#define TERRA_EXCEPTION_MACHINE_CHECK 18
#define TERRA_EXCEPTION_SIMD_FLOATING_POINT 19
#define TERRA_EXCEPTION_VIRTUALIZATION 20
#define TERRA_EXCEPTION_CONTROL_PROTECTION 21

#endif
