#ifndef TERRARIUM_IRQ_H
#define TERRARIUM_IRQ_H

#define TERRA_IRQ_BASE 32
#define TERRA_IRQ_TIMER (TERRA_IRQ_BASE + 0)
#define TERRA_IRQ_KEYBOARD (TERRA_IRQ_BASE + 1)
#define TERRA_IRQ_CASCADE (TERRA_IRQ_BASE + 2)
#define TERRA_IRQ_SERIAL2 (TERRA_IRQ_BASE + 3)
#define TERRA_IRQ_SERIAL1 (TERRA_IRQ_BASE + 4)
#define TERRA_IRQ_PARALLEL2 (TERRA_IRQ_BASE + 5)
#define TERRA_IRQ_FLOPPY (TERRA_IRQ_BASE + 6)
#define TERRA_IRQ_PARALLEL1 (TERRA_IRQ_BASE + 7)
#define TERRA_IRQ_RTC (TERRA_IRQ_BASE + 8)
#define TERRA_IRQ_MOUSE (TERRA_IRQ_BASE + 12)
#define TERRA_IRQ_ATA_PRIMARY (TERRA_IRQ_BASE + 14)
#define TERRA_IRQ_ATA_SECONDARY (TERRA_IRQ_BASE + 15)

#endif
